[[SFML]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f71270e2cc33916b48c41e53535ec08ccc5457be"
os = "windows"

    [[SFML.download]]
    sha256 = "509e5a68a7e9504b02690aa421b5c2048963775598324883b5c828a885667013"
    url = "https://github.com/JuliaBinaryWrappers/SFML_jll.jl/releases/download/SFML-v2.5.1+2/SFML.v2.5.1.i686-w64-mingw32-cxx03.tar.gz"
[[SFML]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38b43be5f8ff0ad599ee3f9dbcf2c7e4fb0921a3"
os = "windows"

    [[SFML.download]]
    sha256 = "41e8c78918bad33244f1227eec5e9eb13b02fc20b1662cf2fe56aab46ee220bc"
    url = "https://github.com/JuliaBinaryWrappers/SFML_jll.jl/releases/download/SFML-v2.5.1+2/SFML.v2.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[SFML]]
arch = "x86_64"
git-tree-sha1 = "aae09ace27dd3d875811f98143a39f642bae6f33"
os = "macos"

    [[SFML.download]]
    sha256 = "73171bf4288dc32d1be079b85d5f4e0077e3566be078625dd61dfaa34c0a1147"
    url = "https://github.com/JuliaBinaryWrappers/SFML_jll.jl/releases/download/SFML-v2.5.1+2/SFML.v2.5.1.x86_64-apple-darwin.tar.gz"
[[SFML]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22dac5d7c8129e44fb067066d718caca1e6a2b7b"
libc = "glibc"
os = "linux"

    [[SFML.download]]
    sha256 = "b6f7e7470af272d179e5002f048d00ef814e6e6151b6abebf0593732060a1849"
    url = "https://github.com/JuliaBinaryWrappers/SFML_jll.jl/releases/download/SFML-v2.5.1+2/SFML.v2.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SFML]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d012bbe1e6cf5ae1d0a42f23c2aee6dc06a1902"
os = "windows"

    [[SFML.download]]
    sha256 = "ec169ccdfb55e83db3e6348f10e5fffa041b313e909e37a77fec5acb42f55596"
    url = "https://github.com/JuliaBinaryWrappers/SFML_jll.jl/releases/download/SFML-v2.5.1+2/SFML.v2.5.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[SFML]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb2f4cb0b5832d8c5dd295f02593883a92b6867a"
os = "windows"

    [[SFML.download]]
    sha256 = "728b14ae1b80f8e66f459507b8ff29e95768253e12a09d652fabd2d8c9763d54"
    url = "https://github.com/JuliaBinaryWrappers/SFML_jll.jl/releases/download/SFML-v2.5.1+2/SFML.v2.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
