# Autogenerated wrapper script for SFML_jll for x86_64-apple-darwin
export libsfml_audio, libsfml_graphics, libsfml_network, libsfml_system, libsfml_window

using Libglvnd_jll
using Ogg_jll
using FLAC_jll
using FreeType2_jll
using libvorbis_jll
using Xorg_libXrandr_jll
using Xorg_libX11_jll
using OpenAL_jll
JLLWrappers.@generate_wrapper_header("SFML")
JLLWrappers.@declare_library_product(libsfml_audio, "@rpath/libsfml-audio.2.5.dylib")
JLLWrappers.@declare_library_product(libsfml_graphics, "@rpath/libsfml-graphics.2.5.dylib")
JLLWrappers.@declare_library_product(libsfml_network, "@rpath/libsfml-network.2.5.dylib")
JLLWrappers.@declare_library_product(libsfml_system, "@rpath/libsfml-system.2.5.dylib")
JLLWrappers.@declare_library_product(libsfml_window, "@rpath/libsfml-window.2.5.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Libglvnd_jll, Ogg_jll, FLAC_jll, FreeType2_jll, libvorbis_jll, Xorg_libXrandr_jll, Xorg_libX11_jll, OpenAL_jll)
    JLLWrappers.@init_library_product(
        libsfml_audio,
        "lib/libsfml-audio.2.5.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsfml_graphics,
        "lib/libsfml-graphics.2.5.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsfml_network,
        "lib/libsfml-network.2.5.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsfml_system,
        "lib/libsfml-system.2.5.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsfml_window,
        "lib/libsfml-window.2.5.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
